# Project default settings
num_samples: 10
model_path: "checkpoints/ddpm/ffhq.pt"
print_config: True
save_png: False
image_size: 256
batch_size: 10
return_artifact: True
experiment_id: test
fisher_iter: 7500
ema_rate: 0.9999
microbatch: -1
num_batch_fisher: 250
num_workers: 0
data_dir: "datasets"
schedule_sampler: "ddim"
fisher_freq: 7500
lr: 0.0001
weight_decay: 0.0
ft_type: "bad"
section_counts: "ddim25"
t_start: 0
t_end: 25

# Diffusion Default setting for FFHQ
clip_denoised: True
use_ddim: True
classifier_scale: 2.0
timestep_respacing: "25"
num_channels: 256
dropout: 0.1
num_head_channels: 64
num_res_blocks: 2
resblock_updown: True
attention_resolutions: "32,16,8"
class_cond: False
use_fp16: False
use_scale_shift_norm: True
num_heads: 4
num_heads_upsample: -1
channel_mult: ""
use_checkpoint: False
use_new_attention_order: False
noise_schedule: "linear"
learn_sigma: True
diffusion_steps: 1000
use_kl: False
predict_xstart: False
rescale_learned_sigmas: False
rescale_timesteps: False
